# Generated by Django 6.0.6 on 2026-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, help_text='For doctors, e.g. Cardiology, Dermatology', max_length=100, null=True),
        ),
    ]
