# Generated by Django 6.0.6 on 2026-06-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='disease_description',
            field=models.TextField(blank=True, help_text='Symptoms described by the patient', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_status',
            field=models.CharField(blank=True, help_text='Previous status or health condition updated by doctor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='prescription',
            field=models.TextField(blank=True, help_text='Prescription written by the doctor', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
